Feature/layout
pet-platform/pet-platform-front pull request #4
Opened 2023-09-22 10:04 UTC by Wannyon

메인페이지 레이아웃 & 헤더, 푸터 레이아웃 수정(위치 및 크기 조정)

2023-09-22 10:49 UTC, PeterJSung commented on app/layout.module.css
> +  width: 98.5vw;
width 를 98.5 로 한이유가있을까요?

2023-09-22 10:50 UTC, PeterJSung commented on app/main/page.tsx
> +import styled from 'styled-components';
스타일드컴포넌트 쓰기로 논의가된것인가요?

2023-09-22 10:52 UTC, PeterJSung commented on app/main/page.tsx
> +      <SubBannar>
이런식으로 반복으로되어있으면 map 이용해서 loop 렌더링하는것이 좋을거같아요

2023-09-22 10:53 UTC, PeterJSung commented on app/layout.module.css
> +  height: 100px;
헤더와 푸터 width 가 다르네요. 혹시이유가있나요?? 왠만하면 전부통일하는게맞을거같아요.

2023-09-22 10:53 UTC, PeterJSung requested changes
리뷰 확인부탁드립니다

2023-09-22 10:55 UTC, Wannyon commented on app/layout.module.css
> +  width: 98.5vw;
100vw를 했을 때 border 양 끝이 짤리게 보이는 현상이 있어서 값을 조정했습니다.

2023-09-22 10:57 UTC, Wannyon commented on app/main/page.tsx
> +import styled from 'styled-components';
아니요 논의가 되진 않았습니다.
디스코드로 의견을 물어봤는데 모든분들이 대답을 주시진 않아서 일단 스타일드를 사용했습니다.
추후에 정해지면 수정하는 방향으로 진행해도 될까요?

2023-09-22 10:58 UTC, Wannyon commented on app/main/page.tsx
> +      <SubBannar>
오 생각 못했었네요.
반영해서 다음 커밋에 수정하겠습니다.

2023-09-22 12:46 UTC, PeterJSung commented on app/layout.module.css
> +  width: 98.5vw;
이거 전체 컨테이너 레이아웃아닌가요? border 가 필요한이유가있을까요?

2023-09-23 07:15 UTC, Wannyon commented on app/layout.module.css
> +  width: 98.5vw;
값을 준 부분은 헤더 부분입니다.
기획문서 디자인에 테두리가 있어서 border를 주었습니다.

2023-10-04 04:57 UTC, PeterJSung commented
@Wannyon 수정사항 재반영해서 커밋부탁드립니다.

2023-10-10 11:55 UTC, PeterJSung approved these changes
LGTM

2023-10-11 19:01 UTC, merged